### ISSUE TITLE
Outstanding issues

### ISSUE THREAD

**Issue by JordiBForgeFlow** [tegin/cb-addons#29]
* [x] Invoices should limit the computation of residual to the move lines that have the same partner (see https://github.com/odoo/odoo/pull/24915, and proposal https://github.com/odoo/odoo/pull/26472)
* [ ] Update l10n_es for taxes for non-deductible purchase taxes (10%, 4%) See https://github.com/odoo/odoo/pull/25930
* [ ]  Allow to set a default warehouse based on the company provided in the context. See https://github.com/odoo/odoo/pull/24063

**Comment by etobella** [comment]
odoo/odoo#29779

**Comment by MiquelRForgeFlow** [comment]
The first have been merged!

**Comment by etobella** [comment]
Great!!
